# Generated by Django 5.0.3 on 2024-03-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInterface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
