# Generated by Django 5.0.3 on 2024-03-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInterface', '0002_useraccounts_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
